### ISSUE TITLE
Debug mode assumes coroutine callables have __name__

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python/asyncio#222]
On python 3.4.3, the following code will work when running without debug mode 
enabled, and raise an exception when run with PYTHONASYNCIODEBUG=1:
```
import asyncio
import functools

@asyncio.coroutine
def func(x, y):
    print('func with x = {} and y = {}'.format(x, y))
    yield from asyncio.sleep(0.1)
    print('exit func')


partial_func = asyncio.coroutine(functools.partial(func, 1))

loop = asyncio.get_event_loop()
try:
    loop.run_until_complete(partial_func(2))
finally:
    loop.close()
```

Line 154 of asyncio.coroutines tries to copy some attributes of the wrapped 
function to its CoroWrapper instance, which fails because the partial object 
has no `__name__`:
```
AttributeError: 'functools.partial' object has no attribute '__name__'
```

Original issue reported on code.google.com by `mwfrojd...@gmail.com` on 31 Mar 2015 at 2:16

**Comment by haypo** [comment]
I wrote a patch to fix the attribute error, but there is still an issue: the program behaves differently in debug mode.

**Comment by gvanrossum** [comment]
When I run the program with `PYTHONASYNCIODEBUG=1`, with the fix in place, I get a traceback:
```
<CoroWrapper func() running at p.py:4, created at /Users/guido/src/asyncio/asyncio/coroutines.py:141> was never yielded from
Coroutine object created at (most recent call last):
  File "p.py", line 15, in <module>
    loop.run_until_complete(partial_func(2))
```
(etc.) but I think this is a red herring, or at least an unrelated issue -- you shouldn't be using partial() to wrap a coroutine, because you're really wrapping the CoroWrapper object at that point. Removing the `@asyncio.coroutine` decorator in front of `def func` resolves this. I've filed #241 about this (but there I also explain I think it's a bug in the example program).
