### ISSUE TITLE
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

### ISSUE THREAD

**Issue by sametmax** [python/asyncio#396]
If you register a signal handler for SIGTERM, start the event loop then kill it with CTRL + C, you get this error:

```
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 431, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 140, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

Minimal code to get the error:

```
import signal
import asyncio

loop = asyncio.get_event_loop()

def bar():
    loop.stop()

loop.add_signal_handler(signal.SIGTERM, bar)
loop.run_forever()
```

This will not occur if you register a handler for another signal, such as SIGINT.

**Comment by vxgmichel** [comment]
> This will not occur if you register a handler for another signal, such as SIGINT.

It does actually occur for all signals except `SIGINT` (`SIGINT` has a special treatment in `loop.remove_signal_handler`). This error has been reported on bugs.python.org as [issue32548](http://bugs.python.org/issue23548). I've looked into it, and it turns out this problem is unrelated to asyncio. It can be reproduced using the `_signal` module only:

```python
import _signal

class A:
    def __del__(self):
        _signal.signal(_signal.SIGTERM, _signal.SIG_DFL)

a = A()
```

It also affects python 2. This happens because the `signalmodule` resources are [cleared](https://hg.python.org/cpython/file/default/Modules/signalmodule.c#l1532) before the garbage collector calls `a.__del__`. It causes [this `if` statement](https://hg.python.org/cpython/file/default/Modules/signalmodule.c#l435) to fail and a misleading `TypeError` is raised.

It's quite similar to [issue 14173](http://bugs.python.org/issue14173) (fixed in 2012).

**Comment by sametmax** [comment]
Thanks. Let me close this then, no need for duplicate tickets.
