### ISSUE TITLE
How to get a coroutine id  like getcurrent in greenlet

### ISSUE THREAD

**Issue by 631068264** [python/asyncio#403]
How to get a coroutine id  like getcurrent in greenlet ?

**Comment by Martiusweb** [comment]
Hi,

This is the bug tracker, you should ask your questions on irc (#asyncio on freenode), on the user's mailing list (https://groups.google.com/forum/#!forum/python-tulip) or on a dedicated platform like stackoverflow.

Asyncio has no concept of task/coroutine id, but you can get the current task object with `asyncio.Task.current_task()`.

**Comment by gvanrossum** [comment]
Who is Martin Richard and why is he being rude in our tracker?

**Comment by Martiusweb** [comment]
Hi Guido,

I didn't want to be rude, and I apologize if the tone of my message or my behavior was incorrect.

Victor Stinner gave me rights on the asyncio repo some time ago (before the migration from google code), I thought I could help by doing some basic bug triage, since I don't contribute much code. As it doesn't sound ok, I won't do that again.

**Comment by gvanrossum** [comment]
(I took this offline, I expect it'll work out fine.)
