### ISSUE TITLE
Why are streams slower than 'standard' protocol implementations?

### ISSUE THREAD

**Issue by sebastian-malek** [python/asyncio#412]
[Streams seem to be slower](https://magic.io/blog/uvloop-blazing-fast-python-networking/tcp-bench.html). Why is that so?

**Comment by 1st1** [comment]
I've applied some optimizations to uvloop since that blog post which made streams 20-30% faster.

They are slower than callback/protocol implementation because of an extra layer of abstraction. async/await, Tasks and Futures introduce some overhead. That said, I think it's possible to remove a lot of that overhead by implementing Futures/Tasks/Streams in C, which we're slowly doing now.

**Comment by mayflaver** [comment]
I think if it's possible to remove a lot of that overhead by implementing Futures/Tasks/Streams when parsing protocol and then apply the protocol result async. 

something like https://github.com/mayflaver/sora

**Comment by asvetlov** [comment]
@mayflaver would you explain in details what's the difference between current implementation and your idea?

**Comment by mayflaver** [comment]
@asvetlov  more yield trigger more overhead

**Comment by sebastian-malek** [comment]
Thanks a lot for your explanation! I guess this can be closed now
